apiVersion: cache.denzil-briffa.github.io/v1alpha1
kind: ImageWarmupPolicy
metadata:
  labels:
    app.kubernetes.io/name: kube-image-warmer
    app.kubernetes.io/managed-by: kustomize
  name: imagewarmuppolicy-sample
spec:
  suspend: false
  backoffLimit: 0
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 3600
  maxConcurrentJobs: 4
  #namespaceSelector:
  #  matchLabels:
  #    scan: enabled
  #namespaceList:
  #  - default
  #namespaceSkipList:
  #  - kube-system
  #workLoadSelector:
  #  matchLabels:
  #    image-warmup: enabled
  #workLoadSkipSelector:
  #  matchLabels:
  #    image-warmup: disabled
  #nodeSelector:
  #  matchLabels:
  #    kubernetes.io/hostname: talos-1
  #nodeSkipSelector:
  #  matchLabels:
  #    kubernetes.io/hostname: talos-3