apiVersion: v2
name: image-warmer
description: Scheduled and node-triggered Kubernetes image warming
type: application
version: 0.1.1
appVersion: "0.1.1"
home: https://github.com/Denzil-Briffa/kube-image-warmer
sources:
  - https://github.com/Denzil-Briffa/kube-image-warmer
annotations:
  org.opencontainers.image.source: https://github.com/Denzil-Briffa/kube-image-warmer
